language: node_js

node_js:
  - stable
jobs:
  include:
    - stage: 'Code Quality' # naming the Tests stage
      name: 'Linting' # names the first Tests stage job
      script: yarn run lint:ci

cache:
  yarn: true
  directories:
    - node_modules
